# Generated by Django 3.1.12 on 2025-04-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='url_img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
