# Generated by Django 3.1.12 on 2025-04-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0002_car_url_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='url_img',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
