# Generated by Django 3.1.12 on 2025-04-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0003_auto_20250428_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='url_img',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
