# Generated by Django 3.1.12 on 2025-04-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0004_auto_20250428_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cin',
            field=models.CharField(default=237894, max_length=20),
            preserve_default=False,
        ),
    ]
