# Generated by Django 3.1.12 on 2025-04-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarRental', '0005_client_cin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
